# Generated by Django 5.0.2 on 2024-07-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_managment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
